name: CI

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew build -x lint
